[package]
name = "FinalProject"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = { version = "2.6", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
